name: release

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: warning

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build wheel twine
          python -m build --sdist --wheel --outdir dist/
          twine check --strict dist/*
      - name: Get package version
        run: |
          version=$(python setup.py --version)
          echo "version=$version" >> $GITHUB_ENV
        shell: bash
        id: version
      - uses: rickstaa/action-create-tag@v1
        name: Create Tag
        with:
          tag: v${{ env.version }}
          message: Release ${{ env.version }}
      - name: Create release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: "Release v" + process.env.version,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: "v" + process.env.version,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
      - name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}